### DISCUSSION TITLE
Kubernetes Ingress with microk8s, MetalLB, and the NGINX Ingress Controller | benbrougher.tech

### DISCUSSION THREAD

**Discussion by giscus** [moutansos/benbrougher-tech#46] [Comments]
# Kubernetes Ingress with microk8s, MetalLB, and the NGINX Ingress Controller | benbrougher.tech

How to use microk8s to create an ingress using MetalLB and the NGINX ingress controller

https://benbrougher.tech/posts/microk8s-ingress/

**Comment by l5** [comment]
Thanks for sharing; the post has definitely helped me!

I was not able to directly apply the `ingress.yml` and needed to make some changes:
* indentation
* host names contained paths; my microk8s did not like that, so I've removed those
* The container images seem to be private (`ghcr.io/moutansos/helocontainers:latest`)

My resulting file looks like this:

```
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-microk8s
  labels:
    app: nginx-ingress-microk8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - host: "api.mysite.net"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service1
            port:
              number: 80
  - host: "api.myothersite.net"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service2
            port:
              number: 80
  - host: "api.myothersite.net"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service2
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: <<LOAD BALANCER IP HERE>>
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

```

While I have not changed the images to public ones, your blog post helped me significantly; thanks again!
