### ISSUE TITLE
service-2.yml typo for kind: Service

### ISSUE THREAD

**Issue by uniuuu** [moutansos/benbrougher-tech#52]
Hi @moutansos 

In the service-2.yml the kind: Service is specified as **service3**  see the config below.
https://github.com/moutansos/benbrougher-tech/blob/master/src/pages/posts/microk8s-ingress.md

```
# service-2.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: ghcr.io/moutansos/helocontainers:latest
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: HELLOCONTAINERS_MESSAGE
              value: 'Hello from Service 2!'
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service3
  type: ClusterIP
```
