### ISSUE TITLE
For service-1 in ingress the path specified as path: "/"  not path: "/(.*)"

### ISSUE THREAD

**Issue by uniuuu** [moutansos/benbrougher-tech#54]
Hi @moutansos

The service-1 cannot respond if to request hello page. 
If to change path in ingress.yml to  **path: "/(.*)"** then the page starts to work.

```
spec:
  rules:
  - host: "api.mysite.net"
    http:
      paths:
      - pathType: Prefix
        path: "/(.*)"
        backend:
          service:
            name: service1
            port:
              number: 80


```
